### ISSUE TITLE
Wrong pointer used in memset in the realloc_zero() function of boot0img.c

### ISSUE THREAD

**Issue by martinayotte** [zador-blood-stained/u-boot-pine64-armbian#1]
Someone post this issue : 
https://github.com/igorpecovnik/lib/issues/446
I've dig with gdb and find out that : 
In boot0img.c line # 280, the memset was using the old ptr instead of the reallocated one in ret : 
`
memset((char*)ret + *sizeptr, 0, newsize - *sizeptr);
`
This is true in both master and next branch

**Comment by zador-blood-stained** [comment]
Looks like this wasn't an issue even [upstream](https://github.com/apritzel/pine64) until memory size increased with new option and people started using this tool with older compiler (since it worked fine for me on Xenial with gcc5)

I pushed this fix, please test.
