### ISSUE TITLE
Camera, LCD and touch screen support?

### ISSUE THREAD

**Issue by ThomasKaiser** [zador-blood-stained/u-boot-pine64-armbian#3]
What's the best way to incorporate the necessary [camera DT bits](https://github.com/avafinger/OV5640_camera) and LCD and touchscreen changes?

DT stuff could be integrated here and the touch requires also a small driver change IIRC (looked through the Android 7.0 stuff for Pine64 a while ago). I would assume [@vintagewaffle](http://forum.armbian.com/index.php/topic/1917-armbian-running-on-pine64-and-other-a64h5-devices/?p=18668) has this stuff already prepared but lacks the idea how to send/integrate this?

**Comment by zador-blood-stained** [comment]
For camera DT bits - either apply changes to DT directly to this repository or add them as u-boot patches.

For other things - I would prefer to look if @jernejsk disp2 EDID changes can apply to Pine64 kernel, and then see if LCD support can be applied on top. Obviously I won't be able to test touch/LCD stuff due to lack of this hardware.

**Comment by ThomasKaiser** [comment]
Agreed on the display stuff, in case @jernejsk finds the time he can also test out LCD/touch since I sent the equipment, TL Lim sent to me to him in the meantime. But since he said he's not that much in love with u-boot I fear he won't look into auto detection stuff (this would be the nicest thing, to check for the TS controller through `I2C` and then [add the necessary DT bits automagically](https://github.com/ayufan-pine64/device-pine64-common/commit/77a5934753c800a0cd0418d35f28cbecbbebdf0c#commitcomment-19334366) from within `u-boot`).

Decided against to touch the camera stuff *now*  since @avafinger already tried out both OV5460 and Pine's ownS5K4EC and they need different DT stuff. If I understood correctly cameras are also able to be detected through I2C so this would also be a great enhancement (auto detection and loading the necessary DT bits like you [showed in Pine64 boot script](https://github.com/igorpecovnik/lib/commit/18208d706836e4f00899b74384be5fb25d4052fc))

**Comment by ThomasKaiser** [comment]
LOL, and since @jernejsk has also an affected Pine64+ he's also able to test the [proposed fix](https://github.com/longsleep/linux-pine64/compare/pine64-hacks-1.2-gmactxonly).

**Comment by zador-blood-stained** [comment]
> (this would be the nicest thing, to check for the TS controller through I2C and then add the necessary DT bits automagically from within u-boot)

I don't see i2c support in pine64 legacy u-boot, otherwise detection could be done even from boot script.

**Comment by ThomasKaiser** [comment]
Too bad, I thought based on u-boot version that it's just enabling `CONFIG_SYS_I2C*`.

**Comment by zador-blood-stained** [comment]
Well, with enough time and motivation it's not that hard to write a basic i2c driver or at least GPIO driver for soft i2c support.

**Comment by ThomasKaiser** [comment]
Ok, stilll don't know how to proceed properly ("we" being a barrier). Maybe should be added as a 'task' in forum?

**Comment by zador-blood-stained** [comment]
> Ok, stilll don't know how to proceed properly ("we" being a barrier).

Check if anybody is interested in this part, and implement manual switching instead of autodetection in the meantime.

> Maybe should be added as a 'task' in forum?

Don't think this will help, but it's easy enough to write a topic or a post on the forum.

**Comment by jernejsk** [comment]
I don't like much BSP U-Boot due to boot0, issues with compiling at times, sometimes some binaries pops out and so on. But currently, it seems that there is no alternative for A64. At least I don't want to invest much time to make mainline U-Boot compatible with BSP kernel.

Nevertheless, I think adding I2C driver should be relatively easy. I quickly compared I2C registers to those from H3 and they are the same. So it should be possible to backport I2C driver from mainline U-Boot to legacy one. Currently I'm away from my stash of Allwinner boards, so it will have to wait few days.

My changes for H3 disp2 driver should be easily portable to A64 kernel, after HDMI blob is replaced with code. H3 HDMI code should be completely same to A64 binary blob minus one function responsible to CEC. Currently, I lost interest in hacking BSP kernel code for a while. If anyone is interested in further hacking code for EDID modes, I can push code now, but it has few bugs.

I will concentrate on mainline U-Boot and kernel for a while, but I will help with old kernel and u-boot if I can (A64 I2C in U-Boot, for example).

**Comment by zador-blood-stained** [comment]
> But currently, it seems that there is no alternative for A64. At least I don't want to invest much time to make mainline U-Boot compatible with BSP kernel.

Mainline u-boot with proper SPL is available as far as I know (not upstream yet), but it can be used only for mainline kernel. For legacy kernel we are stuck with legacy u-boot.

> Nevertheless, I think adding I2C driver should be relatively easy. I quickly compared I2C registers to those from H3 and they are the same. So it should be possible to backport I2C driver from mainline U-Boot to legacy one. Currently I'm away from my stash of Allwinner boards, so it will have to wait few days.

Even soft I2C is enough to scan the bus for devices, but one of the problems is lack of GPIO driver in u-boot (I may be wrong) and the other is - camera and touchscreen are sitting on different I2C busses.

**Comment by jernejsk** [comment]
> Mainline u-boot with proper SPL is available as far as I know (not upstream yet), but it can be used only for mainline kernel. For legacy kernel we are stuck with legacy u-boot.

I know, that's why I said that.

> Even soft I2C is enough to scan the bus for devices, but one of the problems is lack of GPIO driver in u-boot (I may be wrong) and the other is - camera and touchscreen are sitting on different I2C busses.

Everything could be backported from mainline if there is enough interest. In that case I rather have proper drivers instead bitbanged ones.

**Comment by avafinger** [comment]
I am following you all, maybe i can contribute with something, at least with some ideas.
If i understand correctly what you all want i think the camera thing is a bit more challenging than TS. I had some experience with resistive TS and very litle with Capacitive but AFAIK you can have any capacitive TS model and maker attached to the board without burning it at any time, right? Regarding camera thing you have some different power it should be applied on different sensor, let say:  dvdd_vol (camera module core power voltage), they are different for different sensors, i don't know what would happen if you apply 1.8v for a sensor that accepts the maximum of 1.5v. If i am right, the kernel reads from DTB which sensor is activated and then during probing it reads the sensor ID (i2c), if it is the correct sensor (get a response and ID match) then apply the correct pins voltage as described in the DTB. If i understand what you want, u-boot would read some common address and check the presence of some sensors and pass it as a kernel command, something like camera=OV5640 or camera=S5K4EC or camera= if no sensor present and we would need to have in the DTB an array of sensors config or many individual sensor config to match kernel command line and apply the correct power line. Hope you can understand what i mean...and if does make sense.

**Comment by ThomasKaiser** [comment]
My concern/idea was how to enable users to make use of specific hardware. We could add a bunch of DT files below `/boot/` and tell users to exchange files/contents or add stuff to boot script (which might already be too challenging for some).

Please note: I don't care about every possible hardware out there, currently it's just Pine Inc.'s LCD/TS and S5K4EC/OV5640 since this is what people (might) use and where it's already known what to do to get hardware working. Unfortunately my assumption that I2C would be available in u-boot was wrong but still there might be better ways than shipping with a bunch of `.dtb` files.

For example the boot script. Mikhail demonstrates how easy it is to replace specific DT bits [here](https://github.com/igorpecovnik/lib/blob/26c58b8c8a00edc179bb70ce5ba653b6449f4c42/config/bootscripts/boot-pine64-default.cmd#L49-L56). In a similar way LCD could be activated from within `uEnv.txt` (`UseLCD=true` or something like that lets the bootscript enable the LCD and TS bits and takes HDMI settings for `screen1_output_mode` and not `screen0_output_mode`).

In a similar way we could support both cameras but I've to admit that I've no idea whether boot script has a length limit or not. And unfortunately I've currently no time to look deeper into it anyway :\

BTW: When we played around with dvfs/ths settings for Pine64 back in March I had to learn that some settings are only valid when they go into [`u-boot-with-dtb.bin`](https://github.com/longsleep/build-pine64-image/tree/master/u-boot-postprocess) and get ignored when only available as `.dtb` (dvfs operating points for example). But the settings we're talking about now seem not be affected by that?

**Comment by zador-blood-stained** [comment]
@avafinger 
Can you please post exact DT changes for different cameras to check if separate DT files are needed or changes can be made in u-boot at runtime?

@ThomasKaiser 
So we use manual options for camera and manual for display until/if i2c support is available in u-boot.

**Comment by zador-blood-stained** [comment]
@jernejsk 
Please push your final EDID code (with a list of bugs/considerations 😄 ), I'll try to apply it to current sun8i and pine64 branches.

**Comment by avafinger** [comment]
---- S5K4EC ---
`	vfe@0 {
            device_type = "csi0";
            compatible = "allwinner,sunxi-vfe";
            interrupts = <0x00000000 0x00000054 0x00000004>;
            clocks = <0x00000073 0x00000074 0x00000075 0x00000004 0x00000006 0x00000005>;
            pinctrl-names = "default", "sleep";
            pinctrl-1 = <0x00000077>;
            csi0_sensor_list = <0x00000000>;
            status = "okay";
            pinctrl-0 = <0x000000b1>;
            csi0_mck = <0x00000030 0x00000004 0x00000001 0x00000000 0x00000000 0x00000001 0x00000000>;
            dev@0 {
                csi0_dev0_mname = "s5k4ec";
                csi0_dev0_twi_addr = <0x0000005a>;
                csi0_dev0_pos = "rear";
                csi0_dev0_isp_used = <0x00000001>;
                csi0_dev0_fmt = <0x00000000>;
                csi0_dev0_stby_mode = <0x00000001>;
                csi0_dev0_vflip = <0x00000000>;
                csi0_dev0_hflip = <0x00000000>;
                csi0_dev0_iovdd = "iovdd-csi";
                csi0_dev0_iovdd_vol = <0x002ab980>;
                csi0_dev0_avdd = "avdd-csi";
                csi0_dev0_avdd_vol = <0x002ab980>;
                csi0_dev0_dvdd = "dvdd-csi-18";
                csi0_dev0_dvdd_vol = <0x0016e360>;
                csi0_dev0_flash_used = <0x00000000>;
                csi0_dev0_flash_type = <0x00000002>;
                csi0_dev0_flvdd = "vdd-csi-led";
                csi0_dev0_flvdd_vol = <0x00325aa0>;
                csi0_dev0_act_used = <0x00000000>;
                csi0_dev0_act_name = "ad5820_act";
                csi0_dev0_act_slave = <0x00000018>;
                status = "ok";
                device_type = "csi0_dev0";
                csi0_dev0_afvdd;
                csi0_dev0_afvdd_vol;
                csi0_dev0_power_en;
                csi0_dev0_reset = <0x00000030 0x00000004 0x00000010 0x00000000 0x00000000 0x00000001 0x00000000>;
                csi0_dev0_pwdn = <0x00000030 0x00000004 0x00000011 0x00000000 0x00000000 0x00000001 0x00000000>;
                csi0_dev0_flash_en;
                csi0_dev0_flash_mode;
                csi0_dev0_af_pwdn;
            };
	};`

---- OV5640 ----
`        vfe@0 {
            device_type = "csi0";
            compatible = "allwinner,sunxi-vfe";
            interrupts = <0x00000000 0x00000054 0x00000004>;
            clocks = <0x00000073 0x00000074 0x00000075 0x00000004 0x00000006 0x00000005>;
            pinctrl-names = "default", "sleep";
            pinctrl-1 = <0x00000077>;
            csi0_sensor_list = <0x00000000>;
            status = "okay";
            pinctrl-0 = <0x000000b1>;
            csi0_mck = <0x00000030 0x00000004 0x00000001 0x00000000 0x00000000 0x00000001 0x00000000>;
            dev@0 {
                csi0_dev0_mname = "ov5640";
                csi0_dev0_twi_addr = <0x00000078>;
                csi0_dev0_pos = "rear";
                csi0_dev0_isp_used = <0x00000001>;
                csi0_dev0_fmt = <0x00000000>;
                csi0_dev0_stby_mode = <0x00000001>;
                csi0_dev0_vflip = <0x00000000>;
                csi0_dev0_hflip = <0x00000000>;
                csi0_dev0_iovdd = "iovdd-csi";
                csi0_dev0_iovdd_vol = <0x001b7740>;
                csi0_dev0_avdd = "avdd-csi";
                csi0_dev0_avdd_vol = <0x002ab980>;
                csi0_dev0_dvdd = "dvdd-csi-18";
                csi0_dev0_dvdd_vol = <0x0016e360>;
                csi0_dev0_flash_used = <0x00000000>;
                csi0_dev0_flash_type = <0x00000002>;
                csi0_dev0_flvdd = "vdd-csi-led";
                csi0_dev0_flvdd_vol = <0x00325aa0>;
                csi0_dev0_act_used = <0x00000000>;
                csi0_dev0_act_name = "ad5820_act";
                csi0_dev0_act_slave = <0x00000018>;
                status = "ok";
                device_type = "csi0_dev0";
                csi0_dev0_afvdd;
                csi0_dev0_afvdd_vol;
                csi0_dev0_power_en;
                csi0_dev0_reset = <0x00000030 0x00000004 0x00000010 0x00000000 0x00000000 0x00000001 0x00000000>;
                csi0_dev0_pwdn = <0x00000030 0x00000004 0x00000011 0x00000000 0x00000000 0x00000001 0x00000000>;
                csi0_dev0_flash_en;
                csi0_dev0_flash_mode;
                csi0_dev0_af_pwdn;
            };
	};`

**Comment by zador-blood-stained** [comment]
Comparing those side-by-side: only name, i2c address and vdd voltage are different, so we can put common parts with `status = "disabled"` into default DT files, and then manually adjust status and 3 camera specific properties in the boot script.

**Comment by zador-blood-stained** [comment]
Adjusted DT files here: 5f2c075
Added boot script options: https://github.com/igorpecovnik/lib/commit/47c6d8ebcb113b10a3bfb7abcad9ee38dab8041c

Needs testing.

**Comment by ThomasKaiser** [comment]
> Added boot script options: igorpecovnik/lib@47c6d8e

Great, so in `/boot/uEnv.txt/` now `camera_type=none|s5k4ec|ov5640` can be set and DT is adjusted on the fly :)

@avafinger did you already set up instructions how to test with or use OV5640 with Pine64? Can a FriendlyARM camera module be used here?

**Comment by zador-blood-stained** [comment]
> Great, so in /boot/uEnv.txt/ now camera_type=none|s5k4ec|ov5640 can be set and DT is adjusted on the fly :)

It needs to be set in `/boot/armbianEnv.txt`, `uEnv.txt` is obsolete

**Comment by jernejsk** [comment]
@zador-blood-stained 
Please check latest commit and commit message in https://github.com/jernejsk/linux/tree/hdmi_wip

**Comment by ThomasKaiser** [comment]
Hunting for the necessary bits for LCD and touch support: https://github.com/igorpecovnik/lib/compare/master...mbergstrand:master

- We need [this patch](https://github.com/longsleep/linux-pine64/compare/pine64-hacks-1.2...mbergstrand:master.patch) added to pine64-default
- the [u-boot changes](https://github.com/zador-blood-stained/u-boot-pine64-armbian/compare/master...mbergstrand:master) look like a job for parsing `/boot/armbianEnv.txt` and adjusting boot script?
- adding `gt9xxf_ts` to default module list
- And kernel config should already be up to date due to https://github.com/igorpecovnik/lib/commit/a77c10ae6da1e6606e9490b2c03df1d003eaf1c1 right?

Am a bit angry about myself since I sent the LCD a bit too early to @jernejsk to be able to test through this stuff (especially multi display support, LCD as disp0 and using HDMI as disp1).

@mbergstrand could you look please through the above?

**Comment by mbergstrand** [comment]
That looks correct.

Should there be a completely separate dtb for the LCD? i.e. pine64-plus-lcd.dtb or something.

**Comment by ThomasKaiser** [comment]
@mbergstrand the idea is to *not* provide an additional DT file but to fix the available, deactivate LCD there and based on an environment variable read from armbianEnv.txt then set the specific device bits from boot script (just look into boot.cmd to get the idea).

AFAIK @zador-blood-stained currently looks through @jernejsk's display driver changes first, then a switch in boot script could be tested. In the meantime it would be great if you could send https://github.com/longsleep/linux-pine64/compare/pine64-hacks-1.2...mbergstrand:master as a PR to longsleep so other OS images get touch support automagically too (maybe reference this issue when you send the pull request)

**Comment by mbergstrand** [comment]
@ThomasKaiser Ok I think I have the correct changes ready in my fork. 
BUT, it won't work with longsleeps kernel until the pull request above is accepted.

Should I:
1) Create a pull request to lib with the changes even though they won't work with the kernel which should be ok since they are disabled by default?
2) Create a pull request pointing to my fork of linux-pine64 for kernel source?
3) Don't do anything until pull request is accepted?

**Comment by ThomasKaiser** [comment]
@mbergstrand this looks good to me except of the change to `pine64.conf` (so no to 2) above). If @zador-blood-stained has no objections I would vote for a PR against https://github.com/igorpecovnik/lib

Und until longsleep doesn't merge your PR [this patch](https://github.com/longsleep/linux-pine64/compare/pine64-hacks-1.2...mbergstrand:master.patch) has to be thrown into `userpatches/kernel/pine64-default/` to be able to test.

**Comment by mbergstrand** [comment]
Should I include the patch in my PR against lib?

**Comment by ThomasKaiser** [comment]
> Should I include the patch in my PR against lib?

Yes, this is the best idea since as soon as longsleep accepts your PR the patch simply fails and can then be removed later. I would use `patch/kernel/pine64-default/enable-touchscreen-driver.patch` as name (order of the few pine64-default patches shouldn't matter at all)

**Comment by mbergstrand** [comment]
Great. Thanks for your patience and guidance. Most of this stuff, github included, is pretty new to me.

**Comment by ThomasKaiser** [comment]
> Most of this stuff, github included, is pretty new to me.

You did a great job unlike me (I learned how to merge pull requests more sanely just recently and forgot to apply that to yours). Again, thanks for your help!

**Comment by zador-blood-stained** [comment]
I think this can be closed

**Comment by avafinger** [comment]
Sorry @tkaiser, i missed your question, in case you read this:
Yes, and FriendlyARM OV5640 sensor works on Pine64+, use just the sensor!!!

**Comment by tkaiser** [comment]
FYI you tagged the wrong guy @avafinger ;)
